# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2025 Matt Parsons, 2025 Mercury Technologies, Inc
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.12"]
        # Please keep in sync with slack-web.cabal tested-with field :)
        ghc: ["9.2", "9.4", "9.6", "9.8", "9.10"]
    env:
      CONFIG: "--enable-tests"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build --disable-optimization -j $CONFIG
      - run: cabal v2-test --disable-optimization -j $CONFIG
